### ISSUE TITLE
API KeyError

### ISSUE THREAD

**Issue by v0ku** [triestpa/Cryptocurrency-Analysis-Python#5]
Hi, I have a question: 

I've posted my Quandl API Key into this row: 
`quandl.ApiConfig.api_key = os.environ['API KEY']`

>   File "C:\***\Python\Github\Cryptocurrency Analysis\Cryptocurrency-Pricing-Analysis.py", line 74, in <module>
>     quandl.ApiConfig.api_key = os.environ['API KEY']
>   File "C:\ProgramData\Miniconda3\lib\os.py", line 669, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'API Key'
> [Finished in 1.9s]

I'm working via Mininconda in Sublime Text. Using Jupyter doesn't work either. Any idea?

**Comment by triestpa** [comment]
Hi @v0ku - The line in question is checking your local environment variables for the Quandl API key.  Environment variables keys must be a single word, which is why you might be getting a key error for`API Key`.

If you already have you Quandl API key, you have two options - 
1.  Set the Quandl API key as an environment variable on the command line - `set QUANDL_API_KEY={{PUT YOUR KEY HERE}}`.  And then read the variable from the code with `quandl.ApiConfig.api_key = os.environ['QUANDL_API_KEY']`.
2.  Hardcode your api key directly in the code, by modifying the line to read `quandl.ApiConfig.api_key = {{PUT YOUR KEY HERE}}`, without the os.environ.

**Comment by v0ku** [comment]
Hi! Thx for the reply. option 1 doesnt work for me as a windows user. I've choosen option 2.

Btw: Very inspiring 👍 I didn't do anything with it yet, but I will :-)
